/**
 * Postgres connection + Drizzle handle — embedded pglite ONLY (ADR-003): a
 * file-backed database at `<dataDir>/pgdata`, or fully in-memory when no
 * dataDir is given (the test default). No `DATABASE_URL`/postgres-js tier yet;
 * when a hosted tier lands, this file is the ONE branch point (the store/gateway
 * code above it only ever sees the drizzle query-builder API, identical across
 * drivers — the reference's `db/index.ts` shows the pattern).
 *
 * Migrations live in `packages/server/drizzle` (generated by drizzle-kit
 * `db:generate`, committed) and are applied IN-PROCESS via `runMigrations()` —
 * the pglite tier's only path. Forward-only: an app rollback does NOT roll
 * back schema, so columns are only ever ADDED (ADR-002's additive rule applied
 * to the DB).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { PGlite } from "@electric-sql/pglite";
import { drizzle, type PgliteDatabase } from "drizzle-orm/pglite";

import { businessSchema } from "./schema.js";

export type Db = PgliteDatabase<typeof businessSchema>;

export interface DbHandle {
  db: Db;
  /** The raw pglite client (escape hatch for manual SQL, e.g. index asserts). */
  client: PGlite;
  /** The data dir backing this handle, or null for an in-memory database. */
  dataDir: string | null;
}

/** Open (or create) the database. No `dataDir` ⇒ in-memory (tests). */
export async function createDb(options: { dataDir?: string } = {}): Promise<DbHandle> {
  const dataDir = options.dataDir ?? null;
  const client = new PGlite(dataDir == null ? undefined : path.join(dataDir, "pgdata"));
  const db = drizzle(client, { schema: businessSchema });
  return { db, client, dataDir };
}

/** `packages/server/drizzle`, resolved from EITHER src/ (vitest) or dist/
 *  (built output) — both sit two levels below the package root. */
function migrationsDir(): string {
  const here = path.dirname(fileURLToPath(import.meta.url));
  return path.resolve(here, "../../drizzle");
}

/** Apply pending migrations in-process. A no-op before the first `db:generate`
 *  (folder absent) — boot must still work on a fresh checkout. */
export async function runMigrations(handle: DbHandle): Promise<void> {
  const dir = migrationsDir();
  if (!fs.existsSync(dir)) return;
  const { migrate } = await import("drizzle-orm/pglite/migrator");
  await migrate(handle.db, { migrationsFolder: dir });
}

/** Convenience for tests and boot: open + migrate in one call. */
export async function openMigratedDb(options: { dataDir?: string } = {}): Promise<DbHandle> {
  const handle = await createDb(options);
  await runMigrations(handle);
  return handle;
}

export async function closeDb(handle: DbHandle): Promise<void> {
  await handle.client.close();
}
