import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const packageDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const bundleFile = "loopzhb-wrapper.mjs";
const outfile = path.join(packageDir, "dist", bundleFile);
const manifestFile = path.join(packageDir, "src", "wrapper-artifact.generated.ts");
const checkOnly = process.argv.slice(2).includes("--check");

const result = await build({
  entryPoints: [path.join(packageDir, "src", "wrapper-entry.ts")],
  outfile,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  treeShaking: true,
  metafile: true,
  write: false,
  banner: {
    js: "#!/usr/bin/env node\n// loopzhb terminal-command wrapper — generated, self-contained, secret-free",
  },
});

const externalImports = Object.values(result.metafile.outputs)
  .flatMap((output) => output.imports)
  .filter((entry) => entry.external && !entry.path.startsWith("node:"));
if (externalImports.length > 0) {
  throw new Error(
    `wrapper bundle has non-node external imports: ${externalImports.map((entry) => entry.path).join(", ")}`,
  );
}

const output = result.outputFiles.find((file) => path.resolve(file.path) === path.resolve(outfile));
if (output === undefined || !output.text.startsWith("#!/usr/bin/env node\n")) {
  throw new Error("wrapper bundle output is missing or has no pinned executable header");
}
const digest = createHash("sha256").update(output.contents).digest("hex");
const manifest = `// Generated by scripts/build-wrapper.mjs. Do not edit.\nexport const WRAPPER_BUNDLE_FILE = ${JSON.stringify(bundleFile)};\nexport const WRAPPER_BUNDLE_SHA256 = ${JSON.stringify(digest)};\n`;

if (checkOnly) {
  const [installed, installedManifest] = await Promise.all([
    fs.readFile(outfile),
    fs.readFile(manifestFile, "utf8"),
  ]).catch(() => {
    throw new Error("wrapper bundle or compiled integrity manifest is missing; run pnpm build:wrapper");
  });
  if (!installed.equals(output.contents) || installedManifest !== manifest) {
    throw new Error("wrapper bundle is stale or invalid; run pnpm build:wrapper");
  }
} else {
  await fs.mkdir(path.dirname(outfile), { recursive: true });
  await Promise.all([
    fs.writeFile(outfile, output.contents),
    fs.writeFile(manifestFile, manifest, "utf8"),
    fs.rm(`${outfile}.sha256`, { force: true }),
  ]);
}
